### ISSUE TITLE
could not find "load" function definition

### ISSUE THREAD

**Issue by songyahui** [keil/RegEx#1]
Hi, 

I am very interested in this work, plan to try out this project. but when I make file, there is a "load" function, to load all the needed file. but I could not find where did it defined, since  the compiler complains "ReferenceError: load is not defined"

Or is there any instruction for me to try this project out?

Thank you!

**Comment by keil** [comment]
Hi Songyahui,

I'm sorry for that confusion: we used/developed this project in combination with the SpiderMonkey shell. The load function is a global function to load files by name (cf. [Introduction to the JavaScript shell](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Introduction_to_the_JavaScript_shell).

**Comment by songyahui** [comment]
Hi,


Thank you so much for the fast reply! It works now!


Best,
Yahui
________________________________
发件人: Roman Matthias Keil <notifications@github.com>
发送时间: 2019年8月25日 15:37
收件人: keil/RegEx <RegEx@noreply.github.com>
抄送: songyahui <songyahuiapp@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [keil/RegEx] could not find "load" function definition (#1)


Hi Songyahui,

I'm sorry for that confusion: we used/developed this project in combination with the SpiderMonkey shell. The load function is a global function to load files by name (cf. Introduction to the JavaScript shell<https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Introduction_to_the_JavaScript_shell>.

―
